language: android
jdk:
- oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-24.0.1
  - android-24
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support
  - addon-google_apis-google-24
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Il/GZm58RGOro5IvGT/R9gHOXFXXNUhQkmBAkJnckDm8wgQwelTtIeOQjBjCG5NXk4OpKoS3KoARJGArZMEl4rx10gxm88mzxXSRFVE6/4ShVRJJ6NXMzc66xAfjcWSxBh9Z0Dtjn7IPYfuXKHunD3TT0AGYFlkCwkM2/8QpN9w53Jqn5oPIkiF2dWW3pmBba1nLPpN3R2XopKtfGPiEHtAEBBhCHkEQ5J84tnhfLGl+U4xWxPjdwerVO0tDlxDHBjyB+8UFCF+mI3eGwAkcP839Vfxy6sHKV9T8oLgrV6xj4g9bAz0KMfNILK7agokVBP5g9e15VZgVx27D6WBud8B8MzUQ/ppK9XFMI1ykTgPRpTEcx/FEAT8g2ALbP4xfiOkAMYSCfx9ywMRMMpWihoJNHfS+5N2dKT+YshzXq9X5Tcc0voKfMJ8AUg7djPk+tG4LGS10rkMGJ6jRymaiF3XlDXXvQf5o7baoM3a/Ho+WF4oTsn96PzCcXhu7/76AT1uFz4Z3EfKTltQPvf/sRq4prLbnd5tO1I/Zw9Yw8XuVjoA3wh2mMR39CRz4c+ygDu8CHABJUY9QxR2lQ9ja376a6bjLim+V4hc4CFv7YXeWWPIFVhe3RhJET/YtXqxL13ToN6P6LjOc6VxNwi7BwV/yGn+saCr9rfikmeKVcxg=
  file: app/build/outputs/apk/app-debug.apk
  on:
    tags: true
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
